DEFAULT_MODULE += auto_init_at86rf2xx

USEMODULE += ztimer
USEMODULE += ztimer_usec
USEMODULE += event_thread
USEMODULE += event_thread_highest

ifneq (,$(filter netdev,$(USEMODULE)))
  ifneq (,$(filter gnrc_gomach gnrc_lwmac,$(USEMODULE)))
    USEMODULE += netdev_ieee802154_submac
  else
    USEMODULE += gnrc_netif_ieee802154_mac
  endif
  DEFAULT_MODULE += netdev_ieee802154_oqpsk
endif

# only needed for SPI based variants
ifeq (,$(filter at86rfa1 at86rfr2,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
  FEATURES_REQUIRED += periph_spi
endif
